version: "3.3"

services:

  repo:
    #image: opensciencegrid/repo
    build: .
    volumes:
      - repo-data:/data
      - static-data:/data/repo/osg/archive
    ports:
      - "8080:80"

volumes:
  repo-data:
  static-data:

